# Generated by Django 4.2.25 on 2025-10-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(default='student', max_length=50)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('note', 'Note'), ('video', 'Video'), ('past_paper', 'Past Paper'), ('tutorial', 'Tutorial')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('rating_avg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantTopic',
            fields=[
                ('flag_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('subject', models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importance_score', models.FloatField(default=0)),
                ('subject', models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'unique_together': {('topic_name', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('rating_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
