# Generated by Django 4.2.25 on 2025-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importanttopic',
            unique_together={('topic_name', 'subject', 'created_by')},
        ),
    ]
